"""
Email Notification Service — Phase 3 (fixed).
Reads SMTP settings from config.py (which reads from .env).
Uses run_in_executor so smtplib never blocks the async event loop.
"""
import smtplib
import asyncio
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from config import settings

SMTP_HOST     = settings.smtp_host
SMTP_PORT     = settings.smtp_port
SMTP_USER     = settings.smtp_user
SMTP_PASSWORD = settings.smtp_password
FROM_EMAIL    = settings.from_email or "noreply@fcmas-w.health"


def _fmt_slot(slot_time: str) -> str:
    """Safely format a slot_time ISO string to human-readable."""
    if not slot_time:
        return "TBD"
    try:
        return datetime.fromisoformat(slot_time).strftime("%A, %d %B %Y at %I:%M %p")
    except Exception:
        return slot_time


def _build_confirmation_html(patient_name, doctor_name, specialty, slot_time, appointment_id):
    slot_str = _fmt_slot(slot_time)
    return f"""
    <html><body style="font-family:Arial,sans-serif;background:#0d1117;color:#e6edf3;padding:20px;">
      <div style="max-width:540px;margin:auto;background:#161b22;border-radius:12px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#00c9a7,#0ea5e9);padding:24px;text-align:center;">
          <h1 style="color:#fff;margin:0;font-size:22px;">🏥 FCMAS-W Healthcare</h1>
          <p style="color:rgba(255,255,255,0.85);margin:4px 0 0;">Appointment Confirmation</p>
        </div>
        <div style="padding:28px;">
          <p>Dear <strong>{patient_name}</strong>,</p>
          <p>Your appointment has been <strong style="color:#00c9a7;">confirmed</strong>.</p>
          <table style="width:100%;border-collapse:collapse;margin:16px 0;">
            <tr style="border-bottom:1px solid #30363d;">
              <td style="padding:8px;color:#8b949e;">Doctor</td>
              <td style="padding:8px;font-weight:600;">{doctor_name}</td>
            </tr>
            <tr style="border-bottom:1px solid #30363d;">
              <td style="padding:8px;color:#8b949e;">Specialty</td>
              <td style="padding:8px;">{specialty}</td>
            </tr>
            <tr style="border-bottom:1px solid #30363d;">
              <td style="padding:8px;color:#8b949e;">Date &amp; Time</td>
              <td style="padding:8px;color:#00c9a7;font-weight:600;">{slot_str}</td>
            </tr>
            <tr>
              <td style="padding:8px;color:#8b949e;">Appointment ID</td>
              <td style="padding:8px;font-size:0.8em;color:#8b949e;">{appointment_id}</td>
            </tr>
          </table>
          <p style="color:#f59e0b;font-size:0.9em;">⏰ Please arrive 10 minutes early.</p>
          <p style="color:#8b949e;font-size:0.8em;margin-top:24px;">
            Generated by FCMAS-W Healthcare AI System.
          </p>
        </div>
      </div>
    </body></html>
    """


def _send_sync(to_email: str, subject: str, html_body: str) -> dict:
    """Synchronous SMTP send — called via run_in_executor."""
    if not SMTP_HOST or not SMTP_USER or not SMTP_PASSWORD:
        print(f"\n📧 [EMAIL MOCK] To: {to_email} | {subject}")
        print("   → Add SMTP_HOST/SMTP_USER/SMTP_PASSWORD to .env for real delivery\n")
        return {"sent": True, "method": "console_mock"}

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = FROM_EMAIL
    msg["To"]      = to_email
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=15) as server:
            server.ehlo()
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.sendmail(FROM_EMAIL, to_email, msg.as_string())
        print(f"📧 [EMAIL SENT] To: {to_email} | {subject}")
        return {"sent": True, "method": "smtp"}
    except Exception as e:
        print(f"📧 [EMAIL ERROR] {e}")
        return {"sent": False, "error": str(e)}


async def send_appointment_email(
    to_email: str,
    patient_name: str,
    doctor_name: str,
    specialty: str,
    slot_time: str,
    appointment_id: str,
) -> dict:
    """Send appointment confirmation — SMTP runs in thread pool."""
    if not to_email:
        return {"sent": False, "reason": "no email address"}

    slot_str_short = ""
    if slot_time:
        try:
            slot_str_short = f" on {datetime.fromisoformat(slot_time).strftime('%d %b')}"
        except Exception:
            pass

    subject = f"✅ Appointment Confirmed — {doctor_name}{slot_str_short}"
    html    = _build_confirmation_html(patient_name, doctor_name, specialty, slot_time, appointment_id)

    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _send_sync, to_email, subject, html)


async def send_reminder_email(to_email: str, patient_name: str, doctor_name: str, slot_time: str) -> dict:
    """24-hour reminder email."""
    slot_str = _fmt_slot(slot_time)
    subject = f"⏰ Reminder: Appointment tomorrow — {doctor_name}"
    html = f"""
    <html><body style="font-family:Arial,sans-serif;background:#0d1117;color:#e6edf3;padding:20px;">
      <div style="max-width:540px;margin:auto;background:#161b22;border-radius:12px;padding:28px;">
        <h2 style="color:#f59e0b;">⏰ Appointment Reminder</h2>
        <p>Dear <strong>{patient_name}</strong>,</p>
        <p>This is a reminder that you have an appointment <strong>tomorrow</strong>:</p>
        <p style="background:#1f2937;padding:16px;border-radius:8px;border-left:4px solid #00c9a7;">
          <strong>{doctor_name}</strong><br/>📅 {slot_str}
        </p>
        <p>Please bring any relevant medical reports.</p>
        <p style="color:#8b949e;font-size:0.8em;">FCMAS-W Healthcare AI System</p>
      </div>
    </body></html>
    """
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(None, _send_sync, to_email, subject, html)
