"""
PDF Export Service — Generate diet plan PDFs using reportlab.
Falls back to plain-text if reportlab not installed.
"""
import io
import os
from services.wellness_service import get_diet_plan, generate_diet_pdf_text


def generate_diet_pdf(condition: str, preferences: str = "vegetarian", region: str = "North Indian") -> bytes:
    """
    Generate a PDF diet plan and return as bytes.
    Uses reportlab if available; otherwise returns UTF-8 encoded plain text.
    """
    plan_data = get_diet_plan(condition, preferences, region)

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer
        from reportlab.lib.units import cm

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=2*cm, rightMargin=2*cm,
                                topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()
        elements = []

        # ── Title ──────────────────────────────────────────────────────────
        title_style = ParagraphStyle("title", parent=styles["Heading1"],
                                     fontSize=18, textColor=colors.HexColor("#006B5B"),
                                     spaceAfter=6)
        elements.append(Paragraph("FCMAS-W — 7-Day Diet Plan", title_style))

        sub_style = ParagraphStyle("sub", parent=styles["Normal"],
                                   fontSize=11, textColor=colors.HexColor("#4a7a9b"))
        elements.append(Paragraph(
            f"Condition: <b>{plan_data['condition'].title()}</b> | "
            f"Preference: {plan_data['preferences']} | Region: {plan_data['region']}",
            sub_style))
        elements.append(Spacer(1, 0.3*cm))

        guide_style = ParagraphStyle("guide", parent=styles["Normal"],
                                     fontSize=10, backColor=colors.HexColor("#E8F5F2"),
                                     borderPad=6, borderColor=colors.HexColor("#00C9A7"),
                                     borderWidth=1, borderRadius=4, spaceAfter=10)
        elements.append(Paragraph(f"📋 Guidelines: {plan_data['guidelines']}", guide_style))
        elements.append(Spacer(1, 0.4*cm))

        # ── Meal Table ─────────────────────────────────────────────────────
        header = ["Day", "Breakfast", "Lunch", "Dinner", "Snacks"]
        table_data = [header]
        for day, meals in plan_data["plan"].items():
            table_data.append([
                day, meals["breakfast"], meals["lunch"], meals["dinner"], meals["snacks"]
            ])

        table = Table(table_data, colWidths=[2.2*cm, 4.2*cm, 4.2*cm, 4.2*cm, 2.8*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, 0),  colors.HexColor("#00C9A7")),
            ("TEXTCOLOR",    (0, 0), (-1, 0),  colors.white),
            ("FONTNAME",     (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, 0),  9),
            ("ALIGN",        (0, 0), (-1, -1), "LEFT"),
            ("FONTSIZE",     (0, 1), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F0FBF8")]),
            ("GRID",         (0, 0), (-1, -1), 0.5, colors.HexColor("#D0EDE8")),
            ("VALIGN",       (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING",   (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 0.5*cm))

        # ── Avoid Section ──────────────────────────────────────────────────
        avoid_style = ParagraphStyle("avoid", parent=styles["Normal"],
                                     fontSize=9, textColor=colors.HexColor("#c0392b"))
        elements.append(Paragraph(
            "🚫 Foods to Avoid: " + ", ".join(plan_data["avoid"]), avoid_style))
        elements.append(Spacer(1, 0.3*cm))

        # ── Disclaimer ─────────────────────────────────────────────────────
        disc_style = ParagraphStyle("disc", parent=styles["Normal"],
                                    fontSize=8, textColor=colors.gray)
        elements.append(Paragraph(f"⚕️ {plan_data['disclaimer']}", disc_style))
        elements.append(Spacer(1, 0.2*cm))
        elements.append(Paragraph("Generated by FCMAS-W Healthcare AI System", disc_style))

        doc.build(elements)
        return buffer.getvalue()

    except ImportError:
        # Fallback: plain-text as bytes
        text = generate_diet_pdf_text(plan_data)
        return text.encode("utf-8")
